apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: Application Release with manifest
on:
  workflow_dispatch:
    inputs:
      manifest:
        type: string
        required: true
jobs:
  pre-prod:
    steps:
      - name: Deploy GHAPP
        kind: deploy
        if: ${{ fromJSON(inputs.manifest)['GHA App']['GHA-Component2'].deploy }}
        uses: cloudbees-io/register-deployed-artifact@v1
        with:
          version: ${{ fromJSON(inputs.manifest)['GHA App']['GHA-Component2'].version }}
          url: ${{ fromJSON(inputs.manifest)['GHA App']['GHA-Component2'].url }}
          digest: ${{ fromJSON(inputs.manifest)['GHA App']['GHA-Component2'].digest }}
          target-environment: pre-prod
          name: GHA App
  prod:
    needs: pre-prod
    steps:
      - name: Deploy MyAppAPIs
        kind: deploy
        if: ${{ fromJSON(inputs.manifest)['MyAppAPIs']['MyAppAPIs'].deploy }}
        uses: cloudbees-io/register-deployed-artifact@v1
        with:
          version: ${{ fromJSON(inputs.manifest)['GHA App']['GHA-Component2'].version }}
          url: ${{ fromJSON(inputs.manifest)['GHA App']['GHA-Component2'].url }}
          digest: ${{ fromJSON(inputs.manifest)['GHA App']['GHA-Component2'].digest }}
          target-environment: prod
          name: GHA App